### PR TITLE
Fix wrong crs for wmts layer

### PR DESCRIPTION
**Pull request by vprint**
ACCES.BIOMETHANE layer from this service : https://data.geopf.fr/wmts?SERVICE=WMTS&VERSION=1.0.0 shows these informations:
```
Identifier
    PM_6_16
Crs
    EPSG:2154
```
But the CRS should be EPSG:3857 instead of EPSG:2154.

This PR aims to correct this behaviour. Let me know if I need to make any changes to the code.

### CODE REVIEW

**Comment by vprint** [comment]
Prettier sent an error. I fixed it.

**Review by jahow — COMMENTED** [review]
Thank you!! I'm not sure I understand this change completely, and it breaks a test. Could you adjust the expected results in the associated test to let us see how is the outcome changed?

**Comment by vprintempsPei** [comment]
The supported CRS in the "BigWorldPixel" TileMatrixSet is `urn:ogc:def:crs:OGC:1.3:CRS84` while it's `urn:ogc:def:crs:EPSG:6.18:3:3857` in the test.

extract from `ogcsample.xml` : 
```xml
<TileMatrixSet>
    <ows:Identifier>BigWorldPixel</ows:Identifier>
    <ows:SupportedCRS>urn:ogc:def:crs:OGC:1.3:CRS84</ows:SupportedCRS>
    <WellKnownScaleSet>urn:ogc:def:wkss:OGC:1.0:GlobalCRS84Pixel</WellKnownScaleSet>
```

For "GoogleMapsCompatible" the TileMatrixSet is `urn:ogc:def:crs:EPSG:6.18.3:3857` while it's `urn:ogc:def:crs:EPSG::3857` in the test.

extract from `arcgis.xml` : 
```xml
<TileMatrixSet>
    <ows:Title>GoogleMapsCompatible</ows:Title>
    <ows:Abstract>the wellknown 'GoogleMapsCompatible' tile matrix set defined by OGC WMTS
        specification
    </ows:Abstract>
    <ows:Identifier>GoogleMapsCompatible</ows:Identifier>
    <ows:SupportedCRS>urn:ogc:def:crs:EPSG:6.18.3:3857</ows:SupportedCRS>
    <WellKnownScaleSet>urn:ogc:def:wkss:OGC:1.0:GoogleMapsCompatible</WellKnownScaleSet>
```

**Review by jahow — APPROVED** [review]
Thank you!

**Comment by Desplandis** [comment]
Got this issue a well with `1.1.0`, thanks for fixing it!

**Pull request merged**
